import { Venue } from "@/types";

export const mockVenues: Venue[] = [
  {
    id: "1",
    name: "The Iron Horse",
    slug: "the-iron-horse",
    email: "contact@ironhorse.com",
    phone: "+1-555-0101",
    address: "123 Main Street, City, State 12345",
    description: "A cozy neighborhood bar with great atmosphere",
    image: "/venue1.jpg",
    website: "https://ironhorse.com",
    tags: ["Bar", "Live Music", "Sports Bar", "Trivia Night", "Happy Hour"],
    createdAt: "2024-01-15T10:00:00Z",
    maxGuests: 10,
    reservationTime: 60,
    timeSlotInterval: 15,
    advanceBookingDays: 30,
    operatingHours: {
      monday: { open: "09:00", close: "03:00" },
      tuesday: { open: "09:00", close: "03:00" },
      wednesday: { open: "09:00", close: "03:00" },
      thursday: { open: "09:00", close: "03:00" },
      friday: { open: "09:00", close: "03:00" },
      saturday: { open: "09:00", close: "03:00" },
      sunday: { open: "09:00", close: "03:00" },
    },
  },
  {
    id: "2",
    name: "Rooftop Lounge",
    slug: "rooftop-lounge",
    email: "info@rooftoplounge.com",
    phone: "+1-555-0102",
    address: "456 High Street, City, State 12345",
    description: "Upscale rooftop bar with city views",
    image: "/venue2.jpg",
    website: "https://rooftoplounge.com",
    tags: [
      "Rooftop",
      "Cocktail Lounge",
      "Fine Dining",
      "Outdoor Seating",
      "Private Events",
    ],
    createdAt: "2024-01-20T10:00:00Z",
    maxGuests: 10,
    reservationTime: 60,
    timeSlotInterval: 15,
    advanceBookingDays: 30,
    operatingHours: {
      monday: { open: "09:00", close: "22:00" },
      tuesday: { open: "09:00", close: "22:00" },
      wednesday: { open: "09:00", close: "22:00" },
      thursday: { open: "09:00", close: "22:00" },
      friday: { open: "09:00", close: "22:00" },
      saturday: { open: "09:00", close: "22:00" },
      sunday: { open: "09:00", close: "22:00" },
    },
  },
  {
    id: "3",
    name: "Le Bistro Français",
    slug: "le-bistro-francais",
    email: "reservations@lebistrofrancais.com",
    phone: "+1-555-0201",
    address: "789 Artisan Lane, Downtown District, State 12345",
    description:
      "Authentic French fine dining experience with an award-winning chef and an extensive wine collection. Intimate atmosphere perfect for special occasions.",
    image: "/venue8.jpg",
    website: "https://lebistrofrancais.com",
    tags: ["Fine Dining", "Restaurant", "Private Events", "Wine Bar"],
    createdAt: "2024-02-10T08:00:00Z",
    maxGuests: 6,
    reservationTime: 120,
    timeSlotInterval: 30,
    advanceBookingDays: 60,
    operatingHours: {
      monday: { closed: true },
      tuesday: { open: "17:00", close: "22:00" },
      wednesday: { open: "17:00", close: "22:00" },
      thursday: { open: "17:00", close: "22:00" },
      friday: { open: "17:00", close: "23:00" },
      saturday: { open: "17:00", close: "23:00" },
      sunday: { open: "17:00", close: "21:00" },
    },
  },
  {
    id: "4",
    name: "Hop & Grain Brewery",
    slug: "hop-grain-brewery",
    email: "info@hopgrainbrewery.com",
    phone: "+1-555-0301",
    address: "321 Industrial Way, Warehouse District, State 12345",
    description:
      "Local craft brewery featuring house-brewed beers, pub fare, and live music on weekends. Dog-friendly patio and family atmosphere.",
    image: "/venue7.jpg",
    website: "https://hopgrainbrewery.com",
    tags: [
      "Brewery",
      "Casual Dining",
      "Live Music",
      "Outdoor Seating",
      "Happy Hour",
      "Brunch",
    ],
    createdAt: "2024-01-05T12:00:00Z",
    maxGuests: 20,
    reservationTime: 90,
    timeSlotInterval: 15,
    advanceBookingDays: 14,
    operatingHours: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "00:00" },
      friday: { open: "11:00", close: "01:00" },
      saturday: { open: "10:00", close: "01:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: "5",
    name: "Grand Conference Center",
    slug: "grand-conference-center",
    email: "events@grandconference.com",
    phone: "+1-555-0401",
    address: "1000 Business Plaza, Corporate Park, State 12345",
    description:
      "State-of-the-art event and conference facility with multiple rooms accommodating 10 to 500 guests. Perfect for corporate meetings, seminars, workshops, and private events. Full AV equipment included.",
    image: "/venue3.jpg",
    website: "https://grandconference.com",
    tags: ["Conference", "Seminar", "Private Events"],
    createdAt: "2024-03-01T09:00:00Z",
    maxGuests: 500,
    reservationTime: 240,
    timeSlotInterval: 60,
    advanceBookingDays: 180,
    operatingHours: {
      monday: { open: "07:00", close: "20:00" },
      tuesday: { open: "07:00", close: "20:00" },
      wednesday: { open: "07:00", close: "20:00" },
      thursday: { open: "07:00", close: "20:00" },
      friday: { open: "07:00", close: "20:00" },
      saturday: { open: "08:00", close: "18:00" },
      sunday: { closed: true },
    },
  },
];
